name: Unzip Folder
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract zip
        run: |
          unzip *.zip
          rm *.zip
      - name: Commit unzipped files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Unzipped folder via GitHub Actions"
          git push
          
